version: '3.4'

services:
  db:
    image: ander/my-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile    
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net
    ports:
      - "3308:3306"
    networks:
      - my-network

  restwithaspnet:
    image: ander/restwithaspnet-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"
    links:
      - db
    depends_on:
      - db
    networks:
      - my-network

networks: 
    my-network:
        driver: bridge